CREATE TABLE MENU( -- 메뉴판
    MENUID NUMBER(2) PRIMARY KEY 
  , NAME VARCHAR2(40) NOT NULL 
  , PRICE NUMBER(8) NOT NULL 
);

CREATE TABLE CUSTOMER ( -- 고객 정보
  CUSTID NUMBER(2) PRIMARY KEY, 
  CUSTNAME VARCHAR2(20) NOT NULL, 
  PASSWORD VARCHAR2(20) NOT NULL, 
  PHONE VARCHAR2(20) NOT NULL
);

CREATE TABLE ORDERS( -- 전체 주문내역
    ORDERID NUMBER(2) PRIMARY KEY, 
    CUSTID  NUMBER(2) REFERENCES CUSTOMER (CUSTID),
    TOTALPRICE NUMBER (10) NOT NULL
);

INSERT INTO orders
values (1, 1, 3000);

INSERT INTO orders
values (2, 1, 3000);

INSERT INTO orders
values (3, 2, 5000);

CREATE TABLE ORDERSDETAIL ( -- 주문내역
    MENUID NUMBER(2)REFERENCES MENU(MENUID),
    ORDERID NUMBER(2)REFERENCES ORDERS(ORDERID),
    COUNT NUMBER (2) NOT NULL
);

INSERT INTO ORDERSDETAIL
values (1, 1, 1);

INSERT INTO ORDERSDETAIL
values (2, 2, 1);

INSERT INTO ORDERSDETAIL
values (5, 3, 1);

CREATE TABLE STAMP ( -- 스탬프
  STAMPID VARCHAR2(20) PRIMARY KEY, 
  STAMPCNT NUMBER(2) default 0, 
  CUSTID NUMBER(2) REFERENCES CUSTOMER (CUSTID)
);

CREATE TABLE COUPON ( -- 쿠폰
  COUPONID VARCHAR2(20) PRIMARY KEY, 
  COUPONCNT VARCHAR2(20), 
  STAMPID VARCHAR2(20) REFERENCES STAMP (STAMPID) 
);

CREATE TABLE SALES ( -- 매출
     ORDERNUM NUMBER(8) PRIMARY KEY, 
     ORDERID NUMBER(2) REFERENCES ORDERS(ORDERID),
     COUNT NUMBER(2) NOT NULL ,
     TOTALPRICE NUMBER(10) NOT NULL,
     ORDERDATE DATE NOT NULL
);

insert into sales
values (100, 2, 1, 3000, sysdate);

insert into sales
values (200, 3, 1, 5000, sysdate);

INSERT INTO CUSTOMER (CUSTID, CUSTNAME, PASSWORD, PHONE)
VALUES ('1', '홍길동', 'hong1234', '010-1111-1111')
;

INSERT INTO CUSTOMER (CUSTID, CUSTNAME, PASSWORD, PHONE)
VALUES ('2', '김유신', 'kim1234', '010-2222-2222')
;

INSERT INTO CUSTOMER (CUSTID, CUSTNAME, PASSWORD, PHONE)
VALUES ('3', '김계란', 'egg1234', '010-3333-3333')
;

INSERT INTO CUSTOMER (CUSTID, CUSTNAME, PASSWORD, PHONE)
VALUES ('4', '을지문덕', 'el1234', '010-4444-4444')
;

COMMIT;

SELECT * FROM CUSTOMER
;

select * from menu;

SELECT o.orderid, C.CUSTNAME, J.name, J.price, S.COUNT, S.ORDERDATE
FROM ORDERS O
, SALES S
, CUSTOMER C
, (SELECT ODT.ORDERID, M.NAME, M.PRICE
     FROM ORDERSDETAIL ODT, MENU M 
    WHERE ODT.MENUID = M.MENUID) J
 WHERE O.ORDERID = S.ORDERID 
 AND O.ORDERID = J.ORDERID 
 AND O.CUSTID = C.CUSTID
;

-- SQL 사전작업
-- CUSTID_SEQ 시퀀스 생성 (1 부터 1씩 증가)
CREATE SEQUENCE CUSTID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;    

-- 다시 1부터 하기 위해서 CUSTID_SEQ 삭제 
--[회원 추가하고 다시 1부터 추가하고싶을때 초기화 꼭)
DROP SEQUENCE CUSTID_SEQ;

--CUSTOMER 테이블에 STATUS 컬럼 추가 (계정 활성화, 비활성화 떄문에)
ALTER TABLE CUSTOMER ADD STATUS VARCHAR2(20) DEFAULT 'ACTIVE';
